# Generated by Django 2.2 on 2020-09-20 17:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото для категории')),
                ('slug', models.SlugField(blank=True, verbose_name='Название категории в ссылке')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название рецепта')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание рецепта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('slug', models.SlugField(blank=True, verbose_name='Название рецепта в ссылке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название секции')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='recipes.Recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Шаг')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Дополнительное фото')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method', to='recipes.Section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ингредиента')),
                ('amount', models.FloatField(verbose_name='Количество ингредиента')),
                ('measure', models.CharField(choices=[('kg', 'кг.'), ('gr', 'гр.'), ('l', 'л.'), ('ml', 'мл.'), ('cup', 'ст.'), ('tbsp', 'ст. л.'), ('tsp', 'ч. л.'), ('pc', 'шт.')], default='', max_length=50, verbose_name='Мера ингредиента')),
                ('slug', models.SlugField(blank=True, verbose_name='Название рецепта в ссылке')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.Section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
